### ISSUE TITLE
Exception in Thread, OSX random behaviour

### ISSUE THREAD

**Issue by alexge233** [mps-youtube/mps-youtube#435]
Hello,

I'm running OSX Yosemite with brew.
I have both python 2.7.9 and 3.5 (pip3).
I constantly get exceptions which I can't trace back to a specific error:

> Exception in thread Thread-2:Mb; 00:00:01 [0%]   [>                                                                                                                             ]
> Traceback (most recent call last):
>   File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 914, in _bootstrap_inner
>     self.run()
>   File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 862, in run
>     self._target(_self._args, *_self._kwargs)
>   File "/usr/local/lib/python3.5/site-packages/mps_youtube/main.py", line 2480, in _preload
>     g.streams[ytid], audio=False)
>   File "/usr/local/lib/python3.5/site-packages/mps_youtube/streams.py", line 109, in select
>     streams = [x for x in slist if x['mtype'] == "normal" and okres(x)]
>   File "/usr/local/lib/python3.5/site-packages/mps_youtube/streams.py", line 109, in <listcomp>
>     streams = [x for x in slist if x['mtype'] == "normal" and okres(x)]
>   File "/usr/local/lib/python3.5/site-packages/mps_youtube/streams.py", line 93, in okres
>     return int(x['quality'].split("x")[1]) <= maxres
> IndexError: list index out of range

I am using mplayer (also installed with brew) and I have the feeling that its mplayer that propagates the error.

The random behaviour is as follows:
- some Youtube audios play with no errors produced
- some do not play and don't produce any errors 
- some do not play and I get an exception thrown from some thread (error above)
- some do play with the exception thrown above

Overall, most audios do not play, without any error produced.
Is this possibly related to mpsyt, mplayer or python?

**Comment by ids1024** [comment]
See https://github.com/mps-youtube/mps-youtube/issues/422.

It should be fixed by using the develop branch of pafy.

**Comment by orbea** [comment]
What version of youtube-dl do you have?  This looks similar to https://github.com/mps-youtube/mps-youtube/issues/434 which was solved by upgrading youtube-dl to 2016.02.13.

**Comment by alexge233** [comment]
Just upgraded pafy, although I don't know if it is the develop branch that pip uses:

> Metadata-Version: 2.0
> Name: pafy
> Version: 0.4.3
> Summary: Retrieve YouTube content and metadata
> Home-page: http://np1.github.io/pafy/
> Author: np1
> Author-email: np1nagev@gmail.com
> License: LGPLv3
> Location: /usr/local/lib/python3.5/site-packages
> Requires: youtube-dl

I'm not getting the exceptions anymore, but I keep selecting songs from the list, and they simply don't play. The UI changes the colours (as if about to start playing) and then takes me back to the previous list.

Is there a logfile or some way to see what's happening in the back-end?

**Comment by ids1024** [comment]
By the develop branch I mean the git code that hasn't been released yet, which can be installed with `sudo pip3 install -U https://github.com/mps-youtube/pafy/archive/develop.zip`.

You can try running `mpsyt --debug` and see if that provides any helpful information.

**Comment by alexge233** [comment]
Did the update, still the same behaviour:

- I'm in the song list (alternating pink/red list)
- I press 1 and enter to play the first item
- List tries to get the song (changes to blue)
- It goes straight back to the list.

For some other songs (it appears to be random) it will try to actually get the song, before it goes back to the song list without any errors or exceptions.

I use mpsyt on Debian as well, and never seen this behaviour, could it be related to mplayer not being able to play those streams?

**Comment by ids1024** [comment]
Are you using mpv or mplayer?

**Comment by alexge233** [comment]
> MPlayer 1.2-4.2.1 (C) 2000-2015 MPlayer Team

**Comment by ids1024** [comment]
You can try using mpv instead.

**Comment by alexge233** [comment]
This seems to be the problem, `mplayer` silently refused to play the stream (my guess) whereas `mpv` has no problems playing it. Don't know what causes the exception though.
