### ISSUE TITLE
Invalid item / range when sorting by date in user_order Arch linux.

### ISSUE THREAD

**Issue by scaryvoid** [mps-youtube/mps-youtube#443]
I get this message when I preform a user search with user_order set to date:
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.5/site-packages/mps_youtube/main.py", line 2056, in _preload
    stream = streams.select(streamlist, audio=not video, m4a_ok=m4a)
  File "/usr/lib/python3.5/site-packages/mps_youtube/streams.py", line 99, in select
    streams = [x for x in slist if x['mtype'] == "normal" and okres(x)]
  File "/usr/lib/python3.5/site-packages/mps_youtube/streams.py", line 99, in <listcomp>
    streams = [x for x in slist if x['mtype'] == "normal" and okres(x)]
  File "/usr/lib/python3.5/site-packages/mps_youtube/streams.py", line 83, in okres
    return int(x['quality'].split("x")[1]) <= maxres
IndexError: list index out of range

Then I get this message after I select a video to play:
Invalid item / range entered!                                                                                                                                                                                      [1/10>
> Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.5/site-packages/mps_youtube/main.py", line 2056, in _preload
    stream = streams.select(streamlist, audio=not video, m4a_ok=m4a)
  File "/usr/lib/python3.5/site-packages/mps_youtube/streams.py", line 99, in select
    streams = [x for x in slist if x['mtype'] == "normal" and okres(x)]
  File "/usr/lib/python3.5/site-packages/mps_youtube/streams.py", line 99, in <listcomp>
    streams = [x for x in slist if x['mtype'] == "normal" and okres(x)]
  File "/usr/lib/python3.5/site-packages/mps_youtube/streams.py", line 83, in okres
    return int(x['quality'].split("x")[1]) <= maxres
IndexError: list index out of range

I've tried using the latest mps-youtube-git package from the AUR and also manually installing with pip3 from this repo... same story either way. This started about a month or so ago.

**Comment by ids1024** [comment]
This has been reported already, and fixed in pafy git. Install `python-pafy-git` from the aur.

**Comment by scaryvoid** [comment]
I have this version installed:
aur/python-pafy-git 0.3.66.r7.g737aab6-1 (7, 1.15) [installed: 0.4.3.r14.gae8ad39-1]
    Python API for YouTube - Download videos and retrieve metadata from YouTube.

Just for grins I uninstalled and reinstalled...
Still the same error.

**Comment by ids1024** [comment]
Hm, try running `clearcache`.

**Comment by scaryvoid** [comment]
Ah awesome, that worked. Thank you!
